carrier="KM"
[stations]
    mainroute = [
        "Tłuszcz",
        "Jasienica Mazowiecka",
        "Klembów",
        "Dobczyn",
        "Zagościniec",
        "Wołomin Słoneczna",
        "Wołomin",
        "Kobyłka",
        "Kobyłka-Ossów",
        "Zielonka",
        "Ząbki",
        "Warszawa Zacisze-Wilno",
        "Warszawa Wileńska",
    ]

    [stations.subroutes]
        first= [
            "Ostrołęka",
            "Gierwaty",
            "Goworowo",
            "...",
            "Lucynów",
            "Mostówka",
            "Grzegorzowo"
        ]